# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required 
dist: trusty 
language: cpp 
compiler:
  - gcc
notifications:
  email:
    on_success: never
    on_failure: never
#    recipients:
#      - shaotu.jia
env:
  matrix:
    - USE_DEB=true  ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - USE_DEB=true  ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

matrix:
  allow_failures:
    - env: USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - env: USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

install:
  - sudo apt-get install -y -qq lcov
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

 
script: 
  - source .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script

# Generate code coverage, other artifacts
# ---------------------------------------
after_sucess:
  #- coveralls --data_file=.coverage
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"


